name = "Architects Land - Terre des Civilisations (Client)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e081629b1ad8366f146177793ecac6f016f7ebbacdc29541a45a30d4387bfe88"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
