name = "Architects Land - Terre des Civilisations (Client)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ad8679d93cc967887f63f136b75945ccafba91f8671438d2e2f47288db6986c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
